language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check

# script:
#   - docker run --rm -v $PWD:/app phpqa/phpcs .
#   - docker run --rm -v $PWD:/app phpqa/security-checker security:check
#   - phpunit
#   - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi

deploy:
  provider: heroku
  api_key:
    secure: ASEg0Ak6IUnqxuINF1n8i56jlD+X4fcBRPVmv5pmynVLDH9e6h8JNA3u8Z3O0RZn0LyG3c+q2sL9glpaNsNSCTQ4VnrVYR0arp3SR3UMYD2xh+pXEK/fCXuw86A3iwk0jAaob/DFy5kUghQOQEkRK7BRgAdSHHa5laO/8Hq3ngkVWS9/uKKrw4SWXE0DHg9faIg3gOpA0/JDT/4c1Wi9KhLUQEl4YH2reRW65d+XZtlNdWH5zJgW7xg1VFWvCZcpgh4Utp5ZsE2U0ReKaKhHkThf1s5rNO6lsK362Rt+IgJVJr5TjvSNX72MalXx7V1yHkLxZQoh+ZTOh4ExVm/eYt1Wo5Utw/nwJKDixqNDG3fOioVQCTUv8vqSoQ4Xc6XfmRXq692c2XlcUperYTozbYdbQ3WUQ0shTnLKtyDLKauaTgCXtECVTZ7am+4DZ7ELKcFScQaYeNgMAK5JkaRtew49EW2Mikyb75wB6tUENN5da7zHgb06u2Td2mdX+uGettmQO+YDvfxM3jVUcp5lA1exWV9Q5n4dCqjGRvTJPGT5sfiW0NeZurt5xDziZn+s7YRlAsCXoZ0LDrjh/QEzWMzbQs0ceVO3oAR2fzVUl9XjRKbkSsU/C2zQFBIWfgZM4QzVAvMcP5gMnDjJ4jO4MF5NrYK7ZIJgcu78hBshIzs=
  app: projetdp
  on:
    repo: chakiri/projetDP
    branch: pull-request-master
notifications:
  email:
    recipients:
    - yassir.chakiri12@gmail.com
    on_success: never
    on_failure: always
